version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=ana
      - POSTGRES_DB=my_db
    networks:
      - external_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel info
    networks:
      - external_network


  fake-smtp:
    container_name: fake-smtp
    tty: true
    ports:
      - "4000:80"
      - "2525:25"
    image: rnwood/smtp4dev:v3
    networks:
      - external_network

networks:
  external_network:
    external: true
